"""empty message

Revision ID: e4ccfd297884
Revises: 8fb10a65a570
Create Date: 2021-03-23 13:39:44.928461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ccfd297884'
down_revision = '8fb10a65a570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
